docs: update theming and game configuration, add message screen api doc
deep-entertainment/egoventure-docs pull request #3
Opened 2024-05-26 11:50 UTC by ThmsKnz

Documentation update

2024-06-03 05:24 UTC, dploeger requested changes
Just a small thing. Thanks!

2024-06-03 05:24 UTC, dploeger commented on docs/api/message_screen.gd.md
> +### show\_message
Might need to add code comments to enable a description here

2024-06-12 18:33 UTC, ThmsKnz commented
Thanks for spotting this. I've updated the commit.
I'll create a pull request including the comments together with the debug message feature which I'm testing currently.

2024-10-13 16:46 UTC, ThmsKnz commented
API docs and theming.md have been updated to include also new scene name display in debug mode.

2024-10-30 20:55 UTC, merged